### PR TITLE
Add option to pass in Markdown Converter and Sanitizer files

### PR DESCRIPTION
**Pull request by olumidesan**
Markdown files are hosted in a CDN. I want the option to load them from the app's `static` directory or an alternative CDN.

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
Isn't it simpler to just not call `include_pagedown()` and add your files directly? Can we just add a short note in the docs to this effect?

**Comment by olumidesan** [comment]
It is, actually. I've edited the README.md

**Comment by miguelgrinberg** [comment]
No, what I mean is that there is no need to make any changes to this project. You can just document that you want to use your own JS files you add them manually instead of using `include_pagedown()`.

**Comment by miguelgrinberg** [comment]
Perfect, thanks! By the way, just looked at your profile pic and recognized you. Good to hear from you again, I hope you are keeping safe!

**Comment by olumidesan** [comment]
I am, thankfully, as I trust you are too. It's also good to hear from you!

**Pull request closed without merging**
